#!/usr/bin/env python3
import argparse
import boto3
import inquirer
import os

def parse_arguments():                   
    parser = argparse.ArgumentParser(prog='ssh2aws')
    parser.add_argument('name', nargs='*')

    return parser.parse_args()

def get_user_answer(instances):
    questions = [
      inquirer.List('instance',
		    message="Which instance you wanna connnect to?",
		    choices=instances.keys(),
		),
    ]
    answer = inquirer.prompt(questions)
    return answer

def get_instances(name):
    ec2 = boto3.client('ec2')
    reservations = ec2.describe_instances(Filters=[{'Name':'tag:Name', 'Values':['*{}*'.format(name)]}])
    instances={}
    for reservation in reservations['Reservations']:
        for instance in reservation['Instances']:
            inst_out = {}
            inst_name = ''
            for tag in instance['Tags']:
                if tag['Key'] == 'Name':
                    inst_name = tag['Value']
            inst_out['ip'] = instance['PrivateIpAddress']
            inst_out['lunchtime'] = instance['LaunchTime']
            inst_out['description'] = instance['LaunchTime']
            instances[inst_name] = inst_out
    return instances

def main():
    args = parse_arguments()
    instances = get_instances(args.name[0].lower())
    # print(instances)
    inst_choice = get_user_answer(instances)
    # print(inst_choice)
    os.system('ssh {}'.format(instances[inst_choice['instance']]['ip']))
    # print('ssh {}'.format(instances[inst_choice['instance']]['ip']))


main()
